parameters:
  data:
    name: data
    description: Name of of the user.
    in: body
    required: true
    type: object
    properties:
      name:
        type: string
        example: ayo
      email:
        type: string
        example: yomionisade@gmail.com
      age:
        type: number
        example: 20
