parameters:
  name:
    name: name
    description: Name of of the user.
    in: formData
    required: true
    type: string
  age:
    name: age
    description: Age of the user.
    in: formData
    required: true
    type: integer
  email:
    name: email
    description: email of the user.
    in: formData
    required: true
    type: string
